### PR TITLE
Remove trailing white spaces from script files + fix code/output boxes

### PR DESCRIPTION
**Pull request by mribeirodantas**
This Pull Request consists of:

- [x] Remove trailing white spaces from script files (script1-7.nf)
- [x] Fix/standardize source code / output boxes
  - [x] Command lines should be of CMD type, not BASH
  - [x] All code boxes should have the language set, if applicable
  - [x] One line code boxes shouldn’t have line numbers
  - [x] Boxes with 2 or more lines should always have numbered lines (`linenums`)
  - [x] Output from commands shouldn’t be bash. They should be CMD.
  - [x] Standardize the code blocks
Most of the training code blocks consisted of 4 dashes with [keywords,in,this,format]. Some other times, it used ``` or just indentation.
  - [x] There is a snippet in text format, instead of code block (Section 5.2.9)
- [x] Last check for snippets I failed to see at the first time

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Haven't gone through every change, but LGTM from a skim over and quick check of the preview 👍🏻

**Comment by ewels** [comment]
Shame that we don't have syntax highlighting for Nextflow..

**Comment by ewels** [comment]
NB: Will need to switch all of these to `groovy` instead of `nextflow` if we ever implement those.

**Comment by mribeirodantas** [comment]
In this case, it would be nice to find a way to keep the top-right label nextflow + highlight so that it's clear to the reader what is nextflow and what's plain groovy.

**Pull request merged**
